#!/bin/sh
### BEGIN INIT INFO
# Provides:          smarty-server
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Clever Home Server
### END INIT INFO

DAEMON1="/usr/local/bin/smarty-server"
DAEMON2="/usr/local/bin/esp8266"
#DAEMON3="/usr/local/bin/nrf24l01"

if [ `id -u` -ne 0 ]; then
	echo "You need root privileges to run this script"
	exit 1
fi

start()
{
	start-stop-daemon --start --quiet --background --exec $DAEMON1
	start-stop-daemon --start --quiet --background --exec $DAEMON2
#	start-stop-daemon --start --quiet --background --exec $DAEMON3
	echo "Smarty started"
}

stop()
{
	start-stop-daemon --stop --quiet --exec $DAEMON1
	start-stop-daemon --stop --quiet --exec $DAEMON2
#	start-stop-daemon --stop --quiet --exec $DAEMON3
	echo "Smarty stoped"
}

restart()
{
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		exit 1
	;;
	stop)
		stop
		exit 1
	;;
	reload|restart)
		restart
		exit 1
	;;
	*)
		echo "Usage: {start|stop|restart}"
		exit 1
	;;
esac

exit 0
